-- MySQL Script generated by MySQL Workbench
-- Sex 25 Nov 2016 17:32:12 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sys_permission
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `system_resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system_resources` ;

CREATE TABLE IF NOT EXISTS `system_resources` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT 1,
  `permisison` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system_group` ;

CREATE TABLE IF NOT EXISTS `system_group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(32) NOT NULL,
  `permission_resource_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `permission_resource_id`),
  INDEX `idx_g_r` (`permission_resource_id` ASC),
  CONSTRAINT `fk_g_r`
    FOREIGN KEY (`permission_resource_id`)
    REFERENCES `system_resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system_user` ;

CREATE TABLE IF NOT EXISTS `system_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(120) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `avatar` VARCHAR(255) NOT NULL DEFAULT 'default.png',
  `create_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `user_type` CHAR(1) NOT NULL DEFAULT 'S' COMMENT 'M = master\nG = gerente\nS = suporte\nF = usuario final',
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `can_edit` TINYINT(1) NOT NULL DEFAULT 1,
  `can_login` TINYINT(1) NOT NULL,
  `can_use_web` TINYINT(1) NOT NULL,
  `can_use_api` TINYINT(1) NOT NULL,
  `system_group_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `system_resources_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `system_group_id`, `system_resources_id`),
  INDEX `idx_u_g` (`system_group_id` ASC),
  UNIQUE INDEX `un_username` (`username` ASC),
  INDEX `fk_system_user_system_resources1_idx` (`system_resources_id` ASC),
  CONSTRAINT `fk_u_g`
    FOREIGN KEY (`system_group_id`)
    REFERENCES `system_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_user_system_resources1`
    FOREIGN KEY (`system_resources_id`)
    REFERENCES `system_resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `system_resources`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `system_resources` (`id`, `name`, `permisison`) VALUES (1, 'admin', 7);
INSERT INTO `system_resources` (`id`, `name`, `permisison`) VALUES (2, 'admin', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `system_group`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `system_group` (`id`, `group_name`, `permission_resource_id`) VALUES (1, 'SuperUser', 1);
INSERT INTO `system_group` (`id`, `group_name`, `permission_resource_id`) VALUES (2, 'OwnerUser', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `system_user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `system_user` (`id`, `username`, `password`, `name`, `email`, `avatar`, `create_date`, `update_date`, `delete_date`, `user_type`, `active`, `can_edit`, `can_login`, `can_use_web`, `can_use_api`, `system_group_id`, `system_resources_id`) VALUES (1, 'test', 'pass', 'Test User', 'test@user.com', 'admin.png', '2016-04-16 20:00:00', NULL, NULL, 'M', 1, 1, 1, 1, 1, 1, 1);

COMMIT;

